name: Docker Image CI

on:
  push:
    branches:
      - main  # Le pipeline s'exécute sur chaque push dans la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Récupère le code source

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t dieynaba127/basic-docker-project:latest .

    - name: Push Docker image to DockerHub
      run: docker push dieynaba127/basic-docker-project:latest
